package com.sipgate.sparta.diameter._3gpp.common;

import com.sipgate.sparta.diameter.base.core.avp.AVPDefinition;
import com.sipgate.sparta.diameter.base.core.avp.AVPProvider;
import com.sipgate.sparta.diameter.base.core.avp.GroupedAVP;

import java.net.InetAddress;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;

/**
 * Provides AVP definitions for common 3GPP Diameter interfaces.
 */
public final class _3gppAVPProvider implements AVPProvider {

    @Override
    public Collection<AVPDefinition> getDefinitions() {
        return Arrays.asList(
            // 3GPP TS 29.229, Cx and Dx interfaces
            new AVPDefinition(_3gppConstants.AVP_SUPPORTED_FEATURES, "Supported-Features",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_FEATURE_LIST_ID, "Feature-List-ID",
                Long.class, false, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_FEATURE_LIST, "Feature-List",
                Long.class, false, true, _3gppConstants.VENDOR_ID_3GPP),

            // 3GPP TS 29.329, Sh interface
            new AVPDefinition(_3gppConstants.AVP_MSISDN, "MSISDN",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),

            // 3GPP TS 29.336, S6m/S6n interfaces
            new AVPDefinition(_3gppConstants.AVP_USER_IDENTIFIER, "User-Identifier",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_EXTERNAL_IDENTIFIER, "External-Identifier",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),

            // 3GPP TS 29.272, S6a/S6d, S7a/S7d and S13/S13 interfaces
            new AVPDefinition(_3gppConstants.AVP_EPS_LOCATION_INFORMATION, "EPS-Location-Information",
                GroupedAVP.class, false, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_MME_NUMBER_FOR_MT_SMS, "MME-Number-for-MT-SMS",
                byte[].class, false, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SGSN_NUMBER, "SGSN-Number",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),

            // 3GPP TS 29.173, SLh interface
            new AVPDefinition(_3gppConstants.AVP_SERVING_NODE, "Serving-Node",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),

            // 3GPP TS 29.338, S6c interface
            new AVPDefinition(_3gppConstants.AVP_SM_DELIVERY_OUTCOME, "SM-Delivery-Outcome",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SMS_GMSC_ALERT_EVENT, "SMS-GMSC-Alert-Event",
                Long.class, false, true, _3gppConstants.VENDOR_ID_3GPP),

            // Mandatory AVPs from 3GPP interface specifications (Cx/Dx, S6a/S6d/S7a/S7d/S13, S6c, S6m/S6n)
            new AVPDefinition(_3gppConstants.AVP_DIGEST_REALM, "Digest-Realm",
                String.class, true, false, 0),
            new AVPDefinition(_3gppConstants.AVP_DIGEST_QOP, "Digest-QoP",
                String.class, true, false, 0),
            new AVPDefinition(_3gppConstants.AVP_DIGEST_ALGORITHM, "Digest-Algorithm",
                String.class, true, false, 0),
            new AVPDefinition(_3gppConstants.AVP_DIGEST_HA1, "Digest-HA1",
                String.class, true, false, 0),
            new AVPDefinition(_3gppConstants.AVP_VISITED_NETWORK_IDENTIFIER, "Visited-Network-Identifier",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_PUBLIC_IDENTITY, "Public-Identity",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SERVER_NAME, "Server-Name",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SERVER_CAPABILITIES, "Server-Capabilities",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_MANDATORY_CAPABILITY, "Mandatory-Capability",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_OPTIONAL_CAPABILITY, "Optional-Capability",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_USER_DATA, "User-Data",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SIP_NUMBER_AUTH_ITEMS, "SIP-Number-Auth-Items",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SIP_AUTHENTICATION_SCHEME, "SIP-Authentication-Scheme",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SIP_AUTHENTICATE, "SIP-Authenticate",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SIP_AUTHORIZATION, "SIP-Authorization",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SIP_AUTHENTICATION_CONTEXT, "SIP-Authentication-Context",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SIP_AUTH_DATA_ITEM, "SIP-Auth-Data-Item",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SIP_ITEM_NUMBER, "SIP-Item-Number",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SERVER_ASSIGNMENT_TYPE, "Server-Assignment-Type",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_DEREGISTRATION_REASON, "Deregistration-Reason",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_REASON_CODE, "Reason-Code",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_REASON_INFO, "Reason-Info",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_CHARGING_INFORMATION, "Charging-Information",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_PRIMARY_EVENT_CHARGING_FUNCTION_NAME, "Primary-Event-Charging-Function-Name",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SECONDARY_EVENT_CHARGING_FUNCTION_NAME, "Secondary-Event-Charging-Function-Name",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_PRIMARY_CHARGING_COLLECTION_FUNCTION_NAME, "Primary-Charging-Collection-Function-Name",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SECONDARY_CHARGING_COLLECTION_FUNCTION_NAME, "Secondary-Charging-Collection-Function-Name",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_USER_AUTHORIZATION_TYPE, "User-Authorization-Type",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_USER_DATA_ALREADY_AVAILABLE, "User-Data-Already-Available",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_CONFIDENTIALITY_KEY, "Confidentiality-Key",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_INTEGRITY_KEY, "Integrity-Key",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_ORIGINATING_REQUEST, "Originating-Request",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SUBSCRIPTION_DATA, "Subscription-Data",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_TERMINAL_INFORMATION, "Terminal-Information",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_IMEI, "IMEI",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SOFTWARE_VERSION, "Software-Version",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_QOS_SUBSCRIBED, "QoS-Subscribed",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_ULR_FLAGS, "ULR-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_ULA_FLAGS, "ULA-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_VISITED_PLMN_ID, "Visited-PLMN-Id",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_REQUESTED_EUTRAN_AUTHENTICATION_INFO, "Requested-EUTRAN-Authentication-Info",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_REQUESTED_UTRAN_GERAN_AUTHENTICATION_INFO, "Requested-UTRAN-GERAN-Authentication-Info",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_NUMBER_OF_REQUESTED_VECTORS, "Number-Of-Requested-Vectors",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_RE_SYNCHRONIZATION_INFO, "Re-Synchronization-Info",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_IMMEDIATE_RESPONSE_PREFERRED, "Immediate-Response-Preferred",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_AUTHENTICATION_INFO, "Authentication-Info",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_E_UTRAN_VECTOR, "E-UTRAN-Vector",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_UTRAN_VECTOR, "UTRAN-Vector",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_GERAN_VECTOR, "GERAN-Vector",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_NETWORK_ACCESS_MODE, "Network-Access-Mode",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_HPLMN_ODB, "HPLMN-ODB",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_ITEM_NUMBER, "Item-Number",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_CANCELLATION_TYPE, "Cancellation-Type",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_DSR_FLAGS, "DSR-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_DSA_FLAGS, "DSA-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_CONTEXT_IDENTIFIER, "Context-Identifier",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SUBSCRIBER_STATUS, "Subscriber-Status",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_OPERATOR_DETERMINED_BARRING, "Operator-Determined-Barring",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_ACCESS_RESTRICTION_DATA, "Access-Restriction-Data",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_APN_OI_REPLACEMENT, "APN-OI-Replacement",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_ALL_APN_CONFIGURATIONS_INCLUDED_INDICATOR, "All-APN-Configurations-Included-Indicator",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_APN_CONFIGURATION_PROFILE, "APN-Configuration-Profile",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_APN_CONFIGURATION, "APN-Configuration",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_EPS_SUBSCRIBED_QOS_PROFILE, "EPS-Subscribed-QoS-Profile",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_VPLMN_DYNAMIC_ADDRESS_ALLOWED, "VPLMN-Dynamic-Address-Allowed",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_STN_SR, "STN-SR",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_ALERT_REASON, "Alert-Reason",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_AMBR, "AMBR",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_CSG_SUBSCRIPTION_DATA, "CSG-Subscription-Data",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_CSG_ID, "CSG-Id",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_PDN_GW_ALLOCATION_TYPE, "PDN-GW-Allocation-Type",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_EXPIRATION_DATE, "Expiration-Date",
                Date.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_RAT_FREQUENCY_SELECTION_PRIORITY_ID, "RAT-Frequency-Selection-Priority-ID",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_IDA_FLAGS, "IDA-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_PUA_FLAGS, "PUA-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_NOR_FLAGS, "NOR-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_EQUIPMENT_STATUS, "Equipment-Status",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_REGIONAL_SUBSCRIPTION_ZONE_CODE, "Regional-Subscription-Zone-Code",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_RAND, "RAND",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_XRES, "XRES",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_AUTN, "AUTN",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_KASME, "KASME",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_TRACE_COLLECTION_ENTITY, "Trace-Collection-Entity",
                InetAddress.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_KC, "Kc",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SRES, "SRES",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_PDN_TYPE, "PDN-Type",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_ROAMING_RESTRICTED_DUE_TO_UNSUPPORTED_FEATURE, "Roaming-Restricted-Due-To-Unsupported-Feature",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_TRACE_DATA, "Trace-Data",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_TRACE_REFERENCE, "Trace-Reference",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_TRACE_DEPTH, "Trace-Depth",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_TRACE_NE_TYPE_LIST, "Trace-NE-Type-List",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_TRACE_INTERFACE_LIST, "Trace-Interface-List",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_TRACE_EVENT_LIST, "Trace-Event-List",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_OMC_ID, "OMC-Id",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_GPRS_SUBSCRIPTION_DATA, "GPRS-Subscription-Data",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_COMPLETE_DATA_LIST_INCLUDED_INDICATOR, "Complete-Data-List-Included-Indicator",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_PDP_CONTEXT, "PDP-Context",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_PDP_TYPE, "PDP-Type",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_3GPP2_MEID, "3GPP2-MEID",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SPECIFIC_APN_INFO, "Specific-APN-Info",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_LCS_INFO, "LCS-Info",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_GMLC_NUMBER, "GMLC-Number",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_LCS_PRIVACYEXCEPTION, "LCS-PrivacyException",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SS_CODE, "SS-Code",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SS_STATUS, "SS-Status",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_NOTIFICATION_TO_UE_USER, "Notification-To-UE-User",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_EXTERNAL_CLIENT, "External-Client",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_CLIENT_IDENTITY, "Client-Identity",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_GMLC_RESTRICTION, "GMLC-Restriction",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_PLMN_CLIENT, "PLMN-Client",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SERVICE_TYPE, "Service-Type",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SERVICETYPEIDENTITY, "ServiceTypeIdentity",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_MO_LR, "MO-LR",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_TELESERVICE_LIST, "Teleservice-List",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_TS_CODE, "TS-Code",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_CALL_BARRING_INFO, "Call-Barring-Info",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_IDR_FLAGS, "IDR-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_UVR_FLAGS, "UVR-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_UVA_FLAGS, "UVA-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_VPLMN_CSG_SUBSCRIPTION_DATA, "VPLMN-CSG-Subscription-Data",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_IP_SM_GW_NUMBER, "IP-SM-GW-Number",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_IP_SM_GW_NAME, "IP-SM-GW-Name",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SERVICE_ID, "Service-ID",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SCS_IDENTITY, "SCS-Identity",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SERVICE_PARAMETERS, "Service-Parameters",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_T4_PARAMETERS, "T4-Parameters",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SERVICE_DATA, "Service-Data",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_T4_DATA, "T4-Data",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_HSS_CAUSE, "HSS-Cause",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SIR_FLAGS, "SIR-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_IP_SM_GW_REALM, "IP-SM-GW-Realm",
                String.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SM_RP_MTI, "SM-RP-MTI",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SM_RP_SMEA, "SM-RP-SMEA",
                byte[].class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SRR_FLAGS, "SRR-Flags",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SM_DELIVERY_NOT_INTENDED, "SM-Delivery-Not-Intended",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_MWD_STATUS, "MWD-Status",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_MME_ABSENT_USER_DIAGNOSTIC_SM, "MME-Absent-User-Diagnostic-SM",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_MSC_ABSENT_USER_DIAGNOSTIC_SM, "MSC-Absent-User-Diagnostic-SM",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SGSN_ABSENT_USER_DIAGNOSTIC_SM, "SGSN-Absent-User-Diagnostic SM",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_MME_SM_DELIVERY_OUTCOME, "MME-SM-Delivery-Outcome",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_MSC_SM_DELIVERY_OUTCOME, "MSC-SM-Delivery-Outcome",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SGSN_SM_DELIVERY_OUTCOME, "SGSN-SM-Delivery-Outcome",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_IP_SM_GW_SM_DELIVERY_OUTCOME, "IP-SM-GW-SM-Delivery-Outcome",
                GroupedAVP.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_SM_DELIVERY_CAUSE, "SM-Delivery-Cause",
                Integer.class, true, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_ABSENT_USER_DIAGNOSTIC_SM, "Absent-User-Diagnostic-SM",
                Long.class, true, true, _3gppConstants.VENDOR_ID_3GPP),

            // 3GPP TS 29.212 §5.3.31, 3GPP TS 29.272 §7.3, 3GPP TS 29.273 — shared AVPs promoted for SWx reuse
            new AVPDefinition(_3gppConstants.AVP_RAT_TYPE, "RAT-Type", Integer.class, false, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_ACTIVE_APN, "Active-APN", GroupedAVP.class, false, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_LOCAL_TIME_ZONE, "Local-Time-Zone", GroupedAVP.class, false, true, _3gppConstants.VENDOR_ID_3GPP),
            new AVPDefinition(_3gppConstants.AVP_EMERGENCY_SERVICES, "Emergency-Services", Integer.class, false, true, _3gppConstants.VENDOR_ID_3GPP)
        );
    }
}
