package com.sipgate.sparta.diameter.specextractor._3gpp;

import com.sipgate.sparta.diameter.spec.AvpDef;
import com.sipgate.sparta.diameter.spec.AvpFlagRule;
import org.apache.poi.xwpf.usermodel.IBodyElement;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFTable;
import org.apache.poi.xwpf.usermodel.XWPFTableCell;
import org.apache.poi.xwpf.usermodel.XWPFTableRow;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * 99.9% generated by AI/LLM
 *
 * <p>Reads AVP definition tables from a 3GPP/ETSI {@code .docx}.
 *
 * <p>Walks every table in the document, identifies AVP tables by their
 * column headers ({@code Attribute Name}, {@code AVP Code},
 * {@code Value Type} required at minimum), and emits one
 * {@link AvpDef} per data row.
 *
 * <p>3GPP tables typically have flag columns {@code Must / May /
 * Should not / Must not / May Encrypt}. For each AVP, the {@code M}
 * and {@code V} bits land in exactly one of the four rule columns;
 * {@code May Encrypt} is a {@code Yes}/{@code No} cell.
 */
final class DocxAvpTableReader {

    private static final Set<String> REQUIRED_HEADERS = Set.of(
            "Attribute Name", "AVP Code", "Value Type");

    private static final String COL_NAME = "Attribute Name";
    private static final String COL_CODE = "AVP Code";
    private static final String COL_TYPE = "Value Type";
    private static final String COL_MAY_ENCRYPT = "May Encr.";
    private static final String COL_MUST = "Must";
    private static final String COL_MAY = "May";
    private static final String COL_SHOULD_NOT = "Should not";
    private static final String COL_MUST_NOT = "Must not";

    private DocxAvpTableReader() {
    }

    static List<AvpDef> read(final Path docx, final long vendorId, final List<String> tableCaptions) throws IOException {
        try (final InputStream in = Files.newInputStream(docx)) {
            return read(in, vendorId, tableCaptions);
        }
    }

    static List<AvpDef> read(final InputStream in, final long vendorId, final List<String> tableCaptions) throws IOException {
        final Set<String> wanted = new HashSet<>();
        for (final String caption : tableCaptions) {
            wanted.add(normalize(caption));
        }
        final List<AvpDef> result = new ArrayList<>();
        try (final XWPFDocument doc = new XWPFDocument(in)) {
            String lastCaption = "";
            for (final IBodyElement element : doc.getBodyElements()) {
                if (element instanceof XWPFParagraph paragraph) {
                    final String text = normalize(paragraph.getText());
                    if (!text.isBlank()) {
                        lastCaption = text;
                    }
                } else if (element instanceof XWPFTable table) {
                    if (wanted.contains(lastCaption)) {
                        System.out.println("  matched caption: " + lastCaption);
                        result.addAll(parseTable(table, vendorId));
                    }
                    lastCaption = "";
                }
            }
        }
        return result;
    }

    private static List<String> headerCells(final XWPFTable table, final int rowIndex) {
        if (rowIndex >= table.getRows().size()) {
            return List.of();
        }
        final List<String> result = new ArrayList<>();
        for (final XWPFTableCell cell : table.getRows().get(rowIndex).getTableCells()) {
            result.add(normalize(cell.getText()));
        }
        return result;
    }

    private static boolean looksLikeAvpTable(final XWPFTable table) {
        return findHeaderRowIndex(table) >= 0;
    }

    private static int findHeaderRowIndex(final XWPFTable table) {
        final List<XWPFTableRow> rows = table.getRows();
        final int scanLimit = Math.min(rows.size(), 3);
        for (int i = 0; i < scanLimit; i++) {
            if (headerSet(rows.get(i)).containsAll(REQUIRED_HEADERS)) {
                return i;
            }
        }
        return -1;
    }

    private static Set<String> headerSet(final XWPFTableRow row) {
        final Set<String> result = new HashSet<>();
        for (final XWPFTableCell cell : row.getTableCells()) {
            result.add(canonicalHeader(cell.getText()));
        }
        return result;
    }

    private static String normalize(final String s) {
        return s == null ? "" : s.replaceAll("\\s+", " ").trim();
    }

    // Strips a trailing parenthetical annotation like "(NOTE 2)" so that
    // e.g. "Value Type (NOTE 2)" matches the canonical "Value Type" header.
    private static String canonicalHeader(final String s) {
        return normalize(s).replaceAll("\\s*\\(.*\\)\\s*$", "").trim();
    }

    private static List<AvpDef> parseTable(final XWPFTable table, final long vendorId) {
        final int headerRowIndex = findHeaderRowIndex(table);
        if (headerRowIndex < 0) {
            return List.of();
        }
        final List<XWPFTableRow> rows = table.getRows();
        final Map<String, Integer> columnIndex = columnIndexMap(rows.get(headerRowIndex));
        final List<AvpDef> result = new ArrayList<>();
        for (int i = headerRowIndex + 1; i < rows.size(); i++) {
            final AvpDef def = parseRow(rows.get(i), columnIndex, vendorId);
            if (def != null) {
                result.add(def);
            }
        }
        return result;
    }

    private static Map<String, Integer> columnIndexMap(final XWPFTableRow headerRow) {
        final Map<String, Integer> result = new HashMap<>();
        final List<XWPFTableCell> cells = headerRow.getTableCells();
        for (int i = 0; i < cells.size(); i++) {
            result.put(canonicalHeader(cells.get(i).getText()), i);
        }
        return result;
    }

    private static AvpDef parseRow(final XWPFTableRow row,
                                   final Map<String, Integer> idx,
                                   final long vendorId) {
        final List<XWPFTableCell> cells = row.getTableCells();
        final String name = normalize(cellAt(cells, idx, COL_NAME));
        final String codeStr = normalize(cellAt(cells, idx, COL_CODE)).replaceFirst("\\D.*", "");
        if (name.isBlank() || codeStr.isBlank()) {
            return null;
        }
        final long code;
        try {
            code = Long.parseLong(codeStr);
        } catch (final NumberFormatException e) {
            return null;
        }
        final String valueType = normalize(cellAt(cells, idx, COL_TYPE));
        final AvpFlagRule mandatoryBit = determineFlagRule(cells, idx, 'M');
        final AvpFlagRule vendorSpecificBit = determineFlagRule(cells, idx, 'V');
        final boolean mayBeEncrypted = "Yes".equalsIgnoreCase(normalize(cellAt(cells, idx, COL_MAY_ENCRYPT)));
        // V "must not" means the AVP is not vendor-specific — it belongs to IETF (vendor 0), even when listed in a 3GPP table.
        final long effectiveVendorId = vendorSpecificBit == AvpFlagRule.MUST_NOT ? 0L : vendorId;
        return new AvpDef(effectiveVendorId, code, name, valueType, mandatoryBit, vendorSpecificBit, mayBeEncrypted);
    }

    private static AvpFlagRule determineFlagRule(final List<XWPFTableCell> cells,
                                                 final Map<String, Integer> idx,
                                                 final char bit) {
        if (cellContains(cells, idx, COL_MUST, bit)) return AvpFlagRule.MUST;
        if (cellContains(cells, idx, COL_MAY, bit)) return AvpFlagRule.MAY;
        if (cellContains(cells, idx, COL_SHOULD_NOT, bit)) return AvpFlagRule.SHOULD_NOT;
        if (cellContains(cells, idx, COL_MUST_NOT, bit)) return AvpFlagRule.MUST_NOT;
        return AvpFlagRule.MAY;
    }

    private static boolean cellContains(final List<XWPFTableCell> cells,
                                        final Map<String, Integer> idx,
                                        final String header,
                                        final char bit) {
        return normalize(cellAt(cells, idx, header)).indexOf(bit) >= 0;
    }

    private static String cellAt(final List<XWPFTableCell> cells,
                                 final Map<String, Integer> idx,
                                 final String header) {
        final Integer i = idx.get(header);
        if (i == null || i >= cells.size()) {
            return "";
        }
        return cells.get(i).getText();
    }
}
