package com.sipgate.sparta.diameter.specextractor._3gpp;

import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.SerializationFeature;
import tools.jackson.databind.json.JsonMapper;
import com.sipgate.sparta.diameter.spec.AvpDef;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.util.Locale;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * 99.9% generated by AI/LLM
 *
 * <p>Downloads 3GPP/ETSI specs (zip or bare docx), extracts AVP tables,
 * and writes JSON to the test-resource directories of consuming modules.
 *
 * <p>Run with {@code mvn -pl sparta-diameter-spec-extractor compile
 * exec:java}. Downloads land in {@code ./cache/} at the repository
 * root; JSON outputs land at the repo-root-relative paths declared in
 * {@link #SOURCES}.
 */
public final class ExtractorFor3gpp {

    private static final int VENDOR_ID_3GPP = 10415;

    // How to add new sources and write tests
    // 1. Go to https://www.3gpp.org/ftp/Specs/latest and find your spec
    // 2. Download the document and look for the relevant AVP list table(s)
    // 3. Go to 1 for all referenced specs for their AVPs
    // 4. Put them in this List below
    // 5. Run the main() method once
    // 6. Write your tests in your maven module
    private static final List<SpecSource> SOURCES = List.of(
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29338-j30.zip",
            "sparta-diameter-3gpp-sgdgdd/src/test/resources/sgdgdd-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 6.3.3.1/1: SGd/Gdd specific Diameter AVPs")),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29338-j30.zip",
            "sparta-diameter-3gpp-common/src/test/resources/s6c-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 5.3.3.1/1: S6c specific Diameter AVPs")),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29336-j10.zip",
            "sparta-diameter-3gpp-common/src/test/resources/s6ms6n-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 6.4.1/1: S6m/S6n specific Diameter AVPs")),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29272-j50.zip",
            "sparta-diameter-3gpp-common/src/test/resources/s6as6d-s7as7d-s13-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 7.3.1/1: S6a/S6d, S7a/S7d and S13/S13' specific DiameterAVPs")),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29272-j50.zip",
            "sparta-diameter-3gpp-s6a/src/test/resources/s6as6d-s7as7d-s13-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 7.3.1/1: S6a/S6d, S7a/S7d and S13/S13' specific DiameterAVPs")),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29229-j10.zip",
            "sparta-diameter-3gpp-common/src/test/resources/cxdx-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 6.3.0.1: Diameter Multimedia Application AVPs")),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29229-j10.zip",
            "sparta-diameter-3gpp-cxdx/src/test/resources/cxdx-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 6.3.0.1: Diameter Multimedia Application AVPs")),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29212-j10.zip",
            "sparta-diameter-3gpp-gx/src/test/resources/gx-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 5.3.0.1: Gx specific Diameter AVPs")),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29336-j10.zip",
            "sparta-diameter-3gpp-s6t/src/test/resources/s6t-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 8.4.1-1: S6t specific Diameter AVPs")),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29173-j00.zip",
            "sparta-diameter-3gpp-slh/src/test/resources/slh-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 6.4.1/1: SLh specific Diameter AVPs")),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29061-j10.zip",
            "sparta-diameter-3gpp-s6a/src/test/resources/gi-sgi-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 9a: Gi/Sgi specific AVPs")
        ),
        new SpecSource(
            "https://www.3gpp.org/ftp/Specs/latest/Rel-19/29_series/29214-j30.zip",
            "sparta-diameter-3gpp-rx/src/test/resources/rx-avps.json",
            VENDOR_ID_3GPP,
            List.of("Table 5.3.0.1: Rx specific Diameter AVPs ")
        )
    );

    private static final Path REPO_ROOT = findRepoRoot();
    private static final Path CACHE = REPO_ROOT.resolve("cache");

    private ExtractorFor3gpp() {
    }

    public static void main(final String[] args) throws Exception {
        Files.createDirectories(CACHE);
        if (SOURCES.isEmpty()) {
            System.out.println("No SOURCES configured. Edit ExtractorFor3gpp.SOURCES.");
            return;
        }
        for (final SpecSource source : SOURCES) {
            extract(source);
        }
    }

    private static void extract(final SpecSource source) throws IOException, InterruptedException {
        System.out.println("Processing " + source.url());
        final Path docx = ensureDocx(source.url());
        final List<AvpDef> defs = DocxAvpTableReader.read(docx, source.vendorId(), source.tableCaptions());
        final Path jsonOut = REPO_ROOT.resolve(source.jsonPath());
        writeJson(defs, jsonOut);
        System.out.println("  -> " + source.jsonPath() + " (" + defs.size() + " AVPs)");
    }

    private static Path ensureDocx(final String url) throws IOException, InterruptedException {
        final String basename = url.substring(url.lastIndexOf('/') + 1);
        final Path cached = CACHE.resolve(basename);
        if (!Files.exists(cached)) {
            download(url, cached);
        }
        final String lower = basename.toLowerCase(Locale.ROOT);
        if (lower.endsWith(".zip")) {
            return extractDocxFromZip(cached);
        }
        if (lower.endsWith(".docx")) {
            return cached;
        }
        throw new IllegalArgumentException("Unsupported URL extension (expected .zip or .docx): " + basename);
    }

    private static void download(final String url, final Path target) throws IOException, InterruptedException {
        System.out.println("  downloading " + url);
        final HttpClient client = HttpClient.newBuilder().followRedirects(HttpClient.Redirect.ALWAYS).build();
        final HttpRequest request = HttpRequest.newBuilder(URI.create(url)).GET().build();
        final HttpResponse<Path> response = client.send(request, HttpResponse.BodyHandlers.ofFile(target));
        if (response.statusCode() != 200) {
            Files.deleteIfExists(target);
            throw new IOException("Download failed: HTTP " + response.statusCode() + " for " + url);
        }
    }

    private static Path extractDocxFromZip(final Path zip) throws IOException {
        try (final ZipFile archive = new ZipFile(zip.toFile())) {
            ZipEntry docxEntry = null;
            final var entries = archive.entries();
            while (entries.hasMoreElements()) {
                final ZipEntry e = entries.nextElement();
                if (e.getName().toLowerCase(Locale.ROOT).endsWith(".docx")) {
                    docxEntry = e;
                    break;
                }
            }
            if (docxEntry == null) {
                throw new IOException("No .docx entry found in " + zip);
            }
            final Path out = CACHE.resolve(Path.of(docxEntry.getName()).getFileName());
            if (!Files.exists(out)) {
                try (final InputStream in = archive.getInputStream(docxEntry)) {
                    Files.copy(in, out, StandardCopyOption.REPLACE_EXISTING);
                }
            }
            return out;
        }
    }

    private static void writeJson(final List<AvpDef> defs, final Path target) throws IOException {
        Files.createDirectories(target.getParent());
        final ObjectMapper mapper = JsonMapper.builder()
            .enable(SerializationFeature.INDENT_OUTPUT)
            .build();
        mapper.writeValue(target.toFile(), defs);
    }

    private static Path findRepoRoot() {
        Path dir = Path.of("").toAbsolutePath();
        while (dir != null && !Files.exists(dir.resolve(".git"))) {
            dir = dir.getParent();
        }
        if (dir == null) {
            throw new IllegalStateException("Could not locate repository root (no .git ancestor of " + Path.of("").toAbsolutePath() + ")");
        }
        return dir;
    }
}
