<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sipgate</groupId>
        <artifactId>sparta-diameter</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>sparta-diameter-ietf-drmp</artifactId>
    <name>sparta-diameter-ietf-drmp</name>
    <description>RFC 7944 — Diameter Routing Message Priority (DRMP)</description>

    <dependencies>
        <dependency>
            <groupId>com.sipgate</groupId>
            <artifactId>sparta-diameter-base</artifactId>
        </dependency>
    </dependencies>
</project>
