---
name: Build and upload artifact
on:
  push:
    branches:
      - main
    paths:
      - '**/pom.xml'
      - '**/src/**'

jobs:
  pipeline:
    uses: sipgate/workflows/.github/workflows/pipeline-maven-artifact-default.yaml@main
    with:
      maven_docker_tag: 3.9.14-eclipse-temurin-17
    secrets: inherit
